<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-08T19:34:08 IST" name="Default suite" finished-at="2024-09-08T19:34:08 IST" duration-ms="92">
    <groups>
    </groups>
    <test started-at="2024-09-08T19:34:08 IST" name="Default test" finished-at="2024-09-08T19:34:08 IST" duration-ms="92">
      <class name="UITests.LoginTest">
        <test-method is-config="true" signature="connectwithDB()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="connectwithDB" finished-at="2024-09-08T19:34:08 IST" duration-ms="8" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connectwithDB -->
        <test-method is-config="true" signature="createuser()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="createuser" finished-at="2024-09-08T19:34:08 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createuser -->
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="openBrowser" finished-at="2024-09-08T19:34:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="loginToApp" finished-at="2024-09-08T19:34:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="register()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="register" finished-at="2024-09-08T19:34:08 IST" duration-ms="20" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at UITests.LoginTest.register(LoginTest.java:67)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- register -->
        <test-method is-config="true" signature="logout()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="logout" finished-at="2024-09-08T19:34:08 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method signature="payment()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="payment" finished-at="2024-09-08T19:34:08 IST" depends-on-methods="UITests.LoginTest.register" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method UITests.LoginTest.payment() on instance UITests.LoginTest@20d525 depends on not successfully finished methods 
[UITests.LoginTest.register() on instance UITests.LoginTest@20d525]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method UITests.LoginTest.payment() on instance UITests.LoginTest@20d525 depends on not successfully finished methods 
[UITests.LoginTest.register() on instance UITests.LoginTest@20d525]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- payment -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="loginToApp" finished-at="2024-09-08T19:34:08 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="shoppingCart()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="shoppingCart" finished-at="2024-09-08T19:34:08 IST" duration-ms="2" status="PASS">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "UITests.LoginTest.search()" because "lt" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "UITests.LoginTest.search()" because "lt" is null
at UITests.LoginTest.shoppingCart(LoginTest.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shoppingCart -->
        <test-method is-config="true" signature="logout()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="logout" finished-at="2024-09-08T19:34:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="loginToApp" finished-at="2024-09-08T19:34:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="search()[pri:1, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="search" finished-at="2024-09-08T19:34:08 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method is-config="true" signature="logout()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="logout" finished-at="2024-09-08T19:34:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="removeUser()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="removeUser" finished-at="2024-09-08T19:34:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removeUser -->
        <test-method is-config="true" signature="disconnectDB()[pri:0, instance:UITests.LoginTest@20d525]" started-at="2024-09-08T19:34:08 IST" name="disconnectDB" finished-at="2024-09-08T19:34:08 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- disconnectDB -->
      </class> <!-- UITests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
